# Site settings
title: "Euangelion's Blog"
email: naozhong@gmail.com
description: "Coding Zone"
baseurl: ""
url: "http://euangelion666.github.io"
title_description: ""
title_image: "http://i601.photobucket.com/albums/tt92/naozhong/1.jpg?t=1442491715"
google_analytics: "UA-67802592-1"
disqus_account: euangelion666
post_limit: 10

# Social usernames/URLs
twitter_username: WangSheldon
github_username:  euangelion666
linkedin_link: https://www.linkedin.com/pub/%E5%B0%91%E5%8D%8E-%E7%8E%8B/ab/165/b91
# google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
stackoverflow_link: http://stackoverflow.com/users/4510583/sheldon-wang?tab=profile

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
# exclude: [vendor]
